version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bladesystem-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-admin_password}
      - MONGO_INITDB_DATABASE=bladesystem
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: ["mongod", "--config", "/etc/mongod.conf"]

  backend:
    build: .
    container_name: bladesystem-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB_NAME=bladesystem
      - MONGODB_USER=${MONGODB_USER:-blade_user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-blade_password}
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    name: bladesystem-mongodb-data 